import {
  Briefcase,
  Bus,
  Construction,
  Flag,
  FlaskConical,
  GraduationCap,
  HardHat,
  Home,
  Landmark,
  Leaf,
  type LucideIcon,
  MoreHorizontal,
  Receipt,
  Scale,
  Shield,
  ShieldAlert,
  Stethoscope,
  Tractor,
  Umbrella,
  Wallet,
  Zap,
} from "lucide-react";
import type { ProposalCategory } from "@/types";

export const CATEGORY_META: Record<ProposalCategory, { icon: LucideIcon; className: string }> = {
  Economia: { icon: Wallet, className: "bg-emerald-50 text-emerald-700" },
  Educação: { icon: GraduationCap, className: "bg-blue-50 text-blue-700" },
  Saúde: { icon: Stethoscope, className: "bg-rose-50 text-rose-700" },
  Segurança: { icon: Shield, className: "bg-slate-100 text-slate-700" },
  "Meio ambiente": { icon: Leaf, className: "bg-lime-50 text-lime-700" },
  Trabalho: { icon: Briefcase, className: "bg-indigo-50 text-indigo-700" },
  Impostos: { icon: Receipt, className: "bg-orange-50 text-orange-700" },
  Infraestrutura: { icon: Construction, className: "bg-cyan-50 text-cyan-700" },
  "Administração pública": { icon: Landmark, className: "bg-violet-50 text-violet-700" },
  Agricultura: { icon: Tractor, className: "bg-amber-50 text-amber-700" },
  "Assistência social": { icon: Umbrella, className: "bg-pink-50 text-pink-700" },
  "Ciência e tecnologia": { icon: FlaskConical, className: "bg-sky-50 text-sky-700" },
  Defesa: { icon: ShieldAlert, className: "bg-stone-100 text-stone-700" },
  Emprego: { icon: HardHat, className: "bg-teal-50 text-teal-700" },
  Energia: { icon: Zap, className: "bg-yellow-50 text-yellow-700" },
  Habitação: { icon: Home, className: "bg-fuchsia-50 text-fuchsia-700" },
  Justiça: { icon: Scale, className: "bg-purple-50 text-purple-700" },
  Outros: { icon: MoreHorizontal, className: "bg-gray-100 text-gray-700" },
  Política: { icon: Flag, className: "bg-red-50 text-red-700" },
  Previdência: { icon: Umbrella, className: "bg-green-50 text-green-700" },
  Transporte: { icon: Bus, className: "bg-blue-50 text-blue-700" },
  Tributação: { icon: Receipt, className: "bg-orange-50 text-orange-700" },
};
